### ISSUE TITLE
ensure to use correct naming prefixes

### ISSUE THREAD

**Issue by GitMensch** [OCamlPro/autofonce#19]
AC_ ... distributed macros from autoconf, found in its docs
AT_ ... distributed macros from autoconf, specific for autotest, found in its docs

own prefixes, for example AF_ -> specific for autofonce, GC_ -> specific for gnucobol
made up prefix like OWN_ --> macros that are self-defined

**Comment by lefessan** [comment]
Indeed, I should use `AF_` for the new macros I introduced...

**Comment by lefessan** [comment]
Change made.
