### ISSUE TITLE
FR: add Win32 binaries

### ISSUE THREAD

**Issue by GitMensch** [OCamlPro/autofonce#5]
This would provide a way to execute testsuites (which are portable shell scripts) from source in environments that don't have a shell: win32.
For a start, the code in AT_CHECK may be executed within `bash -c` (so some shell would be required, but later on this could be changed to recognize some commands, or switch to special m4 macros in the testsuite for them, for things like grep and sed).

**Comment by lefessan** [comment]
You mean Windows in general (i.e. win64), or the 32 bits version specifically ? 

For 64 bits, it should be possible by extracting artifacts from the current Github Action, maybe it's possible to also build the 32 bit version there, I should try at some point.

**Comment by GitMensch** [comment]
As far as MS is concerned win32 is "any non 16bit windows". Yes, I've meant in general, and as everything it does uses a new pid boundary 64bit would be enough.

**Comment by lefessan** [comment]
I added uploading the artifacts on Github Actions, and published a generated Windows binary for x86_64 in release v0.6.

I don't have a Windows to try it, so I couldn't check if it works correctly in this environment.

**Comment by lefessan** [comment]
We have now a cross-compilation path to Windows for `autofonce`, so it should be easy now to generate Windows 64 binaries for every next release.

**Comment by GitMensch** [comment]
kind of related as it would provide a win32 testbed: https://github.com/OCamlPro/gnucobol/issues/103
